[versions]
agp = "8.8.0"
androidxCredentials = "1.3.0"
appcompatVersion = "1.6.1"
credentials = "<latest version>"
credentialsPlayServicesAuth = "1.3.0"
credentialsVersion = "1.2.0"
firebaseAuthKtxVersion = "21.0.1"
firebaseBom = "31.2.1"
firebaseBomVersion = "33.12.0"
googleFirebaseAuthKtx = "21.0.5"
googleGoogleid = "1.1.1"
googleid = "<latest version>"
googleidVersion = "1.1.0"
kotlin = "1.9.24"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebaseAuthKtx = "23.2.0"
materialVersion = "1.11.0"
mediationTestSuite = "3.0.0"
firebaseFirestoreKtx = "25.1.3"
googleGmsGoogleServices = "4.4.2"
firebaseFirestore = "25.1.3"
media3CommonKtx = "1.6.0"
playServicesAds = "24.1.0"
playServicesAuth = "21.3.0"
playServicesAuthVersion = "20.1.0"
workRuntimeKtx = "2.10.0"
playServicesFido = "20.0.1"
firebaseDatabase = "21.0.0"

[libraries]
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-credentials-play-services-auth-v130 = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentialsPlayServicesAuth" }
androidx-credentials-v120 = { module = "androidx.credentials:credentials", version.ref = "credentialsVersion" }
androidx-credentials-v130 = { module = "androidx.credentials:credentials", version.ref = "androidxCredentials" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-auth-ktx-v2101 = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtxVersion" }
firebase-auth-ktx-v2105 = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "googleFirebaseAuthKtx" }
firebase-bom-v3121 = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBomVersion" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
googleid-v110 = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleidVersion" }
googleid-v111 = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleGoogleid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
material-v1110 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mediation-test-suite = { group = "com.google.android.ads", name = "mediation-test-suite", version.ref = "mediationTestSuite" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
androidx-media3-common-ktx = { group = "androidx.media3", name = "media3-common-ktx", version.ref = "media3CommonKtx" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-auth-v2010 = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
play-services-fido = { group = "com.google.android.gms", name = "play-services-fido", version.ref = "playServicesFido" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

